import { Platform, StatusBar, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: colors.background,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 10,
  },
  finishBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  finishBtnText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 14,
  },
  statsStrip: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 10,
  },
  statBox: {
    flex: 1,
    alignItems: "flex-start",
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 4,
  },
  statValue: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "bold",
  },
  exerciseCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  exerciseCardActive: {
    borderColor: colors.primary,
    elevation: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  exerciseHeader: {
    paddingVertical: 5,
    marginBottom: 5,
  },
  exerciseName: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: "bold",
  },
  exerciseRestIndicator: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  exerciseRestText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "600",
    marginLeft: 6,
  },
  tableHeader: {
    flexDirection: "row",
    marginBottom: 8,
    alignItems: "center",
  },
  tableHeaderText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  colSetHeader: {
    width: 55,
    textAlign: "center",
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "bold",
  },
  colPrevHeader: {
    flex: 1,
    textAlign: "center",
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "bold",
  },
  colInputHeader: { flex: 1, alignItems: "center", justifyContent: "center" },
  colCheckHeader: { width: 40, alignItems: "center" },

  colSet: {
    width: 55,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  colPrev: { flex: 1, alignItems: "center", justifyContent: "center" },
  colInput: { flex: 1, alignItems: "center", justifyContent: "center" },
  colCheck: { width: 40, alignItems: "center", justifyContent: "center" },
  setRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 5,
  },
  setRowCompleted: {
    backgroundColor: "rgba(34, 197, 94, 0.15)",
  },

  setText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "bold",
  },
  deleteSetBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
  },
  deleteSetLine: {
    width: 8,
    height: 2,
    backgroundColor: "#FFF",
  },
  prevText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  input: {
    backgroundColor: "transparent",
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    width: "100%",
    padding: 0,
  },
  inputDisabled: {
    color: colors.textPrimary,
  },
  checkButton: {
    width: 28,
    height: 24,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  checkButtonInactive: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  checkButtonActive: {
    backgroundColor: "#22C55E",
  },
  addSetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 8,
  },
  addSetText: {
    color: colors.textPrimary,
    fontWeight: "600",
    fontSize: 14,
  },
  cancelWorkoutButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    marginTop: 20,
    marginBottom: 40,
  },
  cancelWorkoutText: {
    color: "#EF4444",
    fontWeight: "bold",
    fontSize: 15,
  },
  floatingRestBanner: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 50,
    paddingTop: 20,
    borderTopColor: colors.border,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  floatingRestAdjustBtn: {
    backgroundColor: colors.background,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  floatingRestAdjustText: {
    color: colors.textPrimary,
    fontWeight: "bold",
    fontSize: 16,
  },
  floatingRestTime: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: "bold",
    fontVariant: ["tabular-nums"],
  },
  floatingRestSkipBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  floatingRestSkipText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  editRestModalContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 25,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  editRestTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
  },
  editRestControls: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 25,
  },
  editRestTimeDisplay: {
    color: colors.textPrimary,
    fontSize: 32,
    fontWeight: "bold",
    fontVariant: ["tabular-nums"],
    marginHorizontal: 25,
  },
  editRestButtonsRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    gap: 15,
  },
  editRestBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  editRestBtnText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  summaryOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    padding: 20,
  },
  summaryContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 25,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 25,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: colors.background,
    padding: 15,
    borderRadius: 12,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: 16,
    flex: 1,
    marginLeft: 10,
  },
  summaryValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
  },
  summaryCloseButton: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  summaryCloseText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  unitOptionBtn: {
    width: "100%",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  unitOptionTitle: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
  },
  unitOptionDesc: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  deleteSetIcon: {
    marginRight: 8,
  },
});
