import { Platform, StatusBar, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  timerContainer: {
    backgroundColor: colors.surface,
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  timerText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
    fontVariant: ["tabular-nums"],
  },
  finishText: { color: colors.primary, fontWeight: "bold", fontSize: 16 },
  routineTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "bold",
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  restBanner: {
    flexDirection: "row",
    backgroundColor: "rgba(34, 197, 94, 0.15)",
    borderColor: colors.primary,
    borderWidth: 1,
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 12,
    padding: 15,
    alignItems: "center",
    justifyContent: "space-between",
  },
  restBannerTitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  restBannerTime: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "bold",
    fontVariant: ["tabular-nums"],
  },
  restControls: { flexDirection: "row", gap: 10, alignItems: "center" },
  restAdjustBtn: {
    backgroundColor: colors.surface,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  restAdjustText: {
    color: colors.textPrimary,
    fontWeight: "bold",
    fontSize: 14,
  },
  restSkipBtn: {
    backgroundColor: colors.textPrimary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  restSkipText: { color: colors.background, fontWeight: "bold", fontSize: 14 },
  exerciseCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  exerciseName: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: "bold",
  },
  tableHeader: { flexDirection: "row", marginBottom: 10, paddingHorizontal: 5 },
  tableHeaderText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  setRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 5,
    borderRadius: 8,
    marginBottom: 5,
  },
  setRowCompleted: { backgroundColor: "rgba(34, 197, 94, 0.1)" },
  setText: { color: colors.textPrimary, fontSize: 16, fontWeight: "600" },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    color: colors.textPrimary,
    paddingVertical: 4,
    paddingHorizontal: 8,
    minWidth: 45,
    textAlign: "center",
    fontWeight: "bold",
  },
  inputDisabled: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    color: colors.textPrimary,
  },
  unitBadge: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginLeft: 6,
  },
  unitText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  checkButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flex: 0.5,
  },
  checkButtonInactive: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  checkButtonActive: { backgroundColor: "#22C55E" },
  addSetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    paddingVertical: 10,
  },
  addSetText: { color: colors.primary, fontWeight: "bold", marginLeft: 5 },
  cancelWorkoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderWidth: 1,
    borderColor: "#EF4444",
    paddingVertical: 15,
    borderRadius: 12,
    marginTop: 40,
    marginBottom: 20,
  },
  cancelWorkoutText: {
    color: "#EF4444",
    fontWeight: "bold",
    fontSize: 16,
  },
  summaryOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    padding: 20,
  },
  summaryContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 25,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 25,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: colors.background,
    padding: 15,
    borderRadius: 12,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: 16,
    flex: 1,
    marginLeft: 10,
  },
  summaryValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
  },
  summaryCloseButton: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  summaryCloseText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 16,
  },
});
