import { Platform, StatusBar, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContainer: { paddingBottom: 20 },
  formContainer: {
    paddingHorizontal: 30,
    paddingBottom: 40,
    paddingTop:
      Platform.OS === "android" ? (StatusBar.currentHeight || 24) + 20 : 60,
  },
  logo: { width: 200, height: 200, alignSelf: "center", marginBottom: 5 },
  title: {
    fontSize: 36,
    fontWeight: "900",
    color: colors.primary,
    textAlign: "center",
    marginBottom: 5,
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: 30,
  },
  infoText: {
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
  },
  avatarContainer: {
    alignSelf: "center",
    marginBottom: 20,
    position: "relative",
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "dashed",
  },
  avatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  avatarText: { color: colors.textSecondary, fontSize: 12, marginTop: 5 },
  editBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: colors.primary,
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.background,
  },
  label: {
    color: colors.textPrimary,
    fontSize: 14,
    marginBottom: 8,
    marginLeft: 5,
  },
  input: {
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    fontSize: 14,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
  },

  forgotPasswordButton: {
    alignSelf: "flex-end",
    marginBottom: 20,
    marginTop: -5,
  },
  forgotPasswordText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  rowInputs: { flexDirection: "row", justifyContent: "space-between" },
  halfInput: { width: "48%" },
  segmentContainer: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 10,
    marginBottom: 20,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
    width: "85%",
    alignSelf: "center",
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  segmentButtonActive: { backgroundColor: colors.primary },
  segmentText: { color: colors.textSecondary, fontSize: 13, fontWeight: "600" },
  segmentTextActive: { color: colors.textPrimary },
  selectableButton: {
    backgroundColor: colors.surface,
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectableButtonActive: {
    borderColor: colors.primary,
    backgroundColor: "rgba(204, 85, 0, 0.1)",
  },
  selectableText: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: "600",
  },
  selectableTextActive: { color: colors.primary },
  toggleButton: { marginTop: 30, alignItems: "center" },
  toggleText: {
    color: colors.textSecondary,
    fontSize: 15,
    textDecorationLine: "underline",
  },
});
