import { Platform, StatusBar, StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "../utils/Responsive";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    scrollContainer: { paddingBottom: verticalScale(20) },
    formContainer: {
      paddingHorizontal: scale(30),
      paddingBottom: verticalScale(40),
      paddingTop:
        Platform.OS === "android"
          ? (StatusBar.currentHeight || verticalScale(24)) + verticalScale(20)
          : verticalScale(60),
    },
    logo: {
      width: scale(200),
      height: scale(200),
      alignSelf: "center",
      marginBottom: verticalScale(5),
    },
    title: {
      fontSize: moderateScale(36),
      fontWeight: "900",
      color: colors.primary,
      textAlign: "center",
      marginBottom: verticalScale(5),
      letterSpacing: scale(2),
    },
    subtitle: {
      fontSize: moderateScale(16),
      color: colors.textSecondary,
      textAlign: "center",
      marginBottom: verticalScale(30),
    },
    infoText: {
      color: colors.textSecondary,
      fontSize: moderateScale(14),
      textAlign: "center",
      marginBottom: verticalScale(20),
      lineHeight: moderateScale(20),
    },
    avatarContainer: {
      alignSelf: "center",
      marginBottom: verticalScale(20),
      position: "relative",
    },
    avatarPlaceholder: {
      width: scale(100),
      height: scale(100),
      borderRadius: scale(50),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
      borderStyle: "dashed",
    },
    avatarImage: {
      width: scale(100),
      height: scale(100),
      borderRadius: scale(50),
      borderWidth: 2,
      borderColor: colors.primary,
    },
    avatarText: {
      color: colors.textSecondary,
      fontSize: moderateScale(12),
      marginTop: verticalScale(5),
    },
    editBadge: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: colors.primary,
      width: scale(30),
      height: scale(30),
      borderRadius: scale(15),
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 3,
      borderColor: colors.background,
    },
    label: {
      color: colors.textPrimary,
      fontSize: moderateScale(14),
      marginBottom: verticalScale(8),
      marginLeft: scale(5),
    },
    input: {
      backgroundColor: colors.surface,
      color: colors.textPrimary,
      borderRadius: scale(10),
      padding: scale(15),
      marginBottom: verticalScale(15),
      fontSize: moderateScale(14),
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
    },

    forgotPasswordButton: {
      alignSelf: "flex-end",
      marginBottom: verticalScale(20),
      marginTop: verticalScale(-5),
    },
    forgotPasswordText: {
      color: colors.primary,
      fontSize: moderateScale(14),
      fontWeight: "600",
    },
    rowInputs: { flexDirection: "row", justifyContent: "space-between" },
    halfInput: { width: "48%" },
    segmentContainer: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: scale(10),
      marginBottom: verticalScale(20),
      padding: scale(4),
      borderWidth: 1,
      borderColor: colors.border,
      width: "85%",
      alignSelf: "center",
    },
    segmentButton: {
      flex: 1,
      paddingVertical: verticalScale(8),
      alignItems: "center",
      borderRadius: scale(8),
      backgroundColor: "transparent",
    },
    segmentButtonActive: { backgroundColor: colors.primary },
    segmentText: {
      color: colors.textSecondary,
      fontSize: moderateScale(13),
      fontWeight: "600",
    },
    segmentTextActive: { color: colors.textPrimary },
    selectableButton: {
      backgroundColor: colors.surface,
      padding: scale(15),
      borderRadius: scale(10),
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    selectableButtonActive: {
      borderColor: colors.primary,
      backgroundColor: "rgba(204, 85, 0, 0.1)",
    },
    selectableText: {
      color: colors.textSecondary,
      fontSize: moderateScale(16),
      fontWeight: "600",
    },
    selectableTextActive: { color: colors.primary },
    toggleButton: { marginTop: verticalScale(30), alignItems: "center" },
    toggleText: {
      color: colors.textSecondary,
      fontSize: moderateScale(15),
      textDecorationLine: "underline",
    },
  });
