import { Platform, StatusBar, StyleSheet } from "react-native";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    //Contenedor principal y scroll
    container: { flex: 1, backgroundColor: colors.background },
    scrollContainer: { paddingBottom: 40 },
    formContainer: { paddingBottom: 60 },

    //Cabecera
    headerContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop:
        Platform.OS === "android" ? (StatusBar.currentHeight || 24) + 1 : 50,
      marginBottom: 0,
      zIndex: 10,
    },
    headerRightActions: {
      flexDirection: "row",
      alignItems: "center",
      paddingRight: 20,
      gap: 15,
    },
    iconButton: { zIndex: 10, padding: 5 },
    headerRightIcons: { flexDirection: "row", gap: 15, zIndex: 10 },

    //Información principal del perfil
    centeredProfileInfo: {
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 25,
      marginTop: 20,
    },
    avatarContainer: { marginBottom: 10, position: "relative" },
    avatarCenterContainer: { alignSelf: "center", marginTop: 10 },
    avatarPlaceholder: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    editBadge: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: colors.primary,
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 3,
      borderColor: colors.background,
    },
    usernameText: {
      fontSize: 22,
      fontWeight: "bold",
      color: colors.textPrimary,
      marginBottom: 15,
    },

    //Estatísticas sociales, biografía y datos públicos
    socialStatsRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 40,
      marginBottom: 15,
    },
    socialStatBox: { alignItems: "center" },
    socialStatNumber: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    socialStatLabel: { fontSize: 14, color: colors.textSecondary },
    bioContainer: {
      paddingHorizontal: 20,
      marginTop: 10,
      marginBottom: 5,
      alignItems: "center",
    },
    bioText: {
      textAlign: "center",
      fontSize: 15,
    },
    publicDataContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 10,
      marginBottom: 15,
    },
    publicDataText: {
      fontSize: 15,
      color: colors.textSecondary,
      fontWeight: "500",
    },

    //Botones de acción (seguir, aceptar/rechazar solicitud, cerrar sesión)
    actionButtonContainer: { width: "100%", marginTop: 10 },
    actionButton: {
      backgroundColor: colors.surface,
      paddingVertical: 10,
      paddingHorizontal: 30,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      width: "100%",
      alignItems: "center",
    },
    actionButtonText: {
      color: colors.textPrimary,
      fontWeight: "bold",
      fontSize: 15,
    },
    followRequestContainer: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "center",
    },
    acceptButton: {
      flex: 1,
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    rejectButton: { flex: 1, backgroundColor: colors.surface },
    rejectButtonText: { color: colors.textPrimary },
    buttonTextWhite: { color: "#FFF" },
    logoutButton: {
      flexDirection: "row",
      backgroundColor: "transparent",
      padding: 15,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 30,
      borderWidth: 1,
      borderColor: "#EF4444",
    },
    logoutText: { color: "#EF4444", fontSize: 16, fontWeight: "bold" },

    //Estados vacíos (perfil sin publicaciones, sin seguidores, perfil privado, etc.)
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    emptyStateTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: "bold",
      marginTop: 20,
      textAlign: "center",
    },
    emptyStateText: {
      color: colors.textSecondary,
      marginTop: 10,
      textAlign: "center",
      fontSize: 16,
    },
    emptyStateActionBtn: {
      marginTop: 30,
      backgroundColor: colors.primary,
      paddingHorizontal: 30,
    },
    privateContainer: { alignItems: "center", marginTop: 40 },
    privateTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: "bold",
      marginTop: 15,
    },
    privateText: { color: colors.textSecondary, marginTop: 5 },

    //Pestañas y segmentos (Publicaciones/Rutinas, Estadísticas, Configuración, etc.)
    segmentContainer: {
      flexDirection: "row",
      backgroundColor: colors.background,
      marginHorizontal: 20,
      marginBottom: 15,
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
      borderBottomWidth: 2,
      borderColor: "transparent",
    },
    segmentButtonActive: { borderColor: colors.primary },

    //Botones de segmento para formularios (editar perfil, cambiar contraseña, etc.)
    formSegmentContainer: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 10,
      marginBottom: 15,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    formSegmentButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 8,
    },
    formSegmentButtonActive: { backgroundColor: colors.primary },
    segmentText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
    },
    segmentTextActive: { color: colors.textPrimary },

    //Historial de actividad, publicaciones, rutinas, etc.
    historySectionContainer: { marginTop: 10, paddingHorizontal: 20 },
    historySectionTitle: { fontSize: 16, marginBottom: 15, marginLeft: 0 },
    emptyHistoryText: {
      color: colors.textSecondary,
      textAlign: "center",
      marginTop: 20,
    },
    historyCard: {
      flexDirection: "column",
      alignItems: "flex-start",
    },
    historyDateText: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 2,
      marginBottom: 4,
    },
    historyStatsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 5,
    },
    loadMoreBtn: {
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 40,
    },
    loadMoreText: { color: colors.primary, fontWeight: "bold" },
    routineCard: {
      backgroundColor: colors.surface,
      padding: 15,
      borderRadius: 10,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    routineInfo: { flex: 1 },
    routineName: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 5,
    },
    routineDetails: {
      color: colors.textSecondary,
      fontSize: 13,
    },
    routineDetailsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 5,
    },
    routineStatText: { color: colors.textSecondary, fontSize: 13 },
    bookmarkBtn: {
      padding: 10,
      backgroundColor: colors.background,
      borderRadius: 10,
    },

    //Modales generales (editar perfil, opciones de publicación, reportar usuario, etc.)
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.7)",
      justifyContent: "flex-end",
      margin: 0,
      padding: 0,
    },
    modalContent: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
      padding: 25,
      width: "100%",
      maxHeight: "85%",
      flexShrink: 1,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: { color: colors.textPrimary, fontSize: 22, fontWeight: "bold" },

    //Modales específicos (opciones de publicación, reportar usuario, etc.)
    optionsModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    optionsModalContent: {
      backgroundColor: colors.background,
      padding: 20,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    optionsModalHandle: {
      width: 40,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 20,
    },
    optionsModalRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 15,
    },
    optionsModalRowBorder: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 15,
      borderTopWidth: 1,
      borderColor: colors.border,
      marginTop: 10,
    },
    optionsModalTextDanger: {
      fontSize: 16,
      color: "#EF4444",
      fontWeight: "600",
    },
    optionsModalText: { fontSize: 16, color: colors.textPrimary },
    optionsModalIcon: { marginRight: 15 },
    reportModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      padding: 20,
    },
    reportModalContent: {
      backgroundColor: colors.background,
      borderRadius: 15,
      padding: 20,
    },
    reportModalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 15,
    },
    reportModalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    reportReasonPrompt: { color: colors.textSecondary, marginBottom: 15 },
    reportInput: {
      backgroundColor: colors.surface,
      color: colors.textPrimary,
      borderRadius: 10,
      padding: 15,
      minHeight: 100,
      textAlignVertical: "top",
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
    },
    reportSubmitBtn: { padding: 15, borderRadius: 10, alignItems: "center" },
    reportSubmitText: { color: "#FFF", fontWeight: "bold", fontSize: 16 },

    //Configuración y ajustes (privacidad, notificaciones, idioma, etc.)
    settingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    settingLabel: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "500",
    },

    //Lista de seguidores/seguidos, solicitudes de seguimiento, etc.
    socialListItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    socialListAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 15,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    socialListAvatarPlaceholder: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 15,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    socialListUsername: {
      flex: 1,
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "600",
    },

    //Inputs de edición de perfil, cambio de contraseña, etc.
    label: {
      color: colors.textSecondary,
      fontSize: 13,
      marginBottom: 6,
      marginLeft: 4,
      fontWeight: "600",
    },
    rowInputs: { flexDirection: "row", justifyContent: "space-between" },
    halfInput: { width: "48%" },
    readOnlyInput: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: colors.textSecondary,
      paddingHorizontal: 0,
    },
  });
