import { Platform, StatusBar, StyleSheet } from "react-native";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    scrollContainer: { paddingBottom: 40 },
    formContainer: { paddingBottom: 60 },

    headerContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop:
        Platform.OS === "android" ? (StatusBar.currentHeight || 24) + 1 : 50,
      marginBottom: 0,
      zIndex: 10,
    },

    centeredProfileInfo: {
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 25,
      marginTop: 0,
    },
    avatarContainer: { marginBottom: 10, position: "relative" },
    avatarPlaceholder: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    editBadge: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: colors.primary,
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 3,
      borderColor: colors.background,
    },
    usernameText: {
      fontSize: 22,
      fontWeight: "bold",
      color: colors.textPrimary,
      marginBottom: 15,
    },

    socialStatsRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 40,
      marginBottom: 15,
    },
    socialStatBox: { alignItems: "center" },
    socialStatNumber: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    socialStatLabel: { fontSize: 14, color: colors.textSecondary },

    publicDataContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 10,
      marginBottom: 15,
    },
    publicDataText: {
      fontSize: 15,
      color: colors.textSecondary,
      fontWeight: "500",
    },

    actionButton: {
      backgroundColor: colors.surface,
      paddingVertical: 10,
      paddingHorizontal: 30,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      width: "100%",
      alignItems: "center",
    },
    actionButtonText: {
      color: colors.textPrimary,
      fontWeight: "bold",
      fontSize: 15,
    },

    segmentContainer: {
      flexDirection: "row",
      backgroundColor: "transparent",
      marginBottom: 20,
      marginHorizontal: 15,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderBottomWidth: 2,
      borderBottomColor: "transparent",
    },
    segmentButtonActive: { borderBottomColor: colors.primary },

    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.7)",
      justifyContent: "flex-end",
      margin: 0,
      padding: 0,
    },
    modalContent: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
      padding: 25,
      width: "100%",
      maxHeight: "85%",
      flexShrink: 1,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: { color: colors.textPrimary, fontSize: 22, fontWeight: "bold" },
    settingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    settingLabel: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "500",
    },
    logoutButton: {
      flexDirection: "row",
      backgroundColor: "transparent",
      padding: 15,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 30,
      borderWidth: 1,
      borderColor: "#EF4444",
    },
    logoutText: { color: "#EF4444", fontSize: 16, fontWeight: "bold" },

    label: {
      color: colors.textSecondary,
      fontSize: 13,
      marginBottom: 6,
      marginLeft: 4,
      fontWeight: "600",
    },
    rowInputs: { flexDirection: "row", justifyContent: "space-between" },
    halfInput: { width: "48%" },

    readOnlyInput: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: colors.textSecondary,
      paddingHorizontal: 0,
    },

    formSegmentContainer: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 10,
      marginBottom: 15,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    formSegmentButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 8,
    },
    formSegmentButtonActive: { backgroundColor: colors.primary },
    segmentText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
    },
    segmentTextActive: { color: colors.textPrimary },

    socialListItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    socialListAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 15,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    socialListAvatarPlaceholder: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 15,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    socialListUsername: {
      flex: 1,
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "600",
    },
    routineCard: {
      backgroundColor: colors.surface,
      padding: 15,
      borderRadius: 10,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    routineInfo: {
      flex: 1,
    },
    routineName: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 5,
    },
    routineDetails: {
      color: colors.textSecondary,
      fontSize: 13,
    },
  });
