import { Platform, StatusBar, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContainer: { paddingBottom: 20 },
  formContainer: {
    paddingHorizontal: 30,
    paddingBottom: 40,
    paddingTop:
      Platform.OS === "android" ? (StatusBar.currentHeight || 24) + 20 : 60,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: "900",
    color: colors.primary,
    letterSpacing: 1,
  },
  avatarContainer: {
    alignSelf: "center",
    marginBottom: 10,
    position: "relative",
  },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  editBadge: {
    position: "absolute",
    bottom: 5,
    right: 5,
    backgroundColor: colors.primary,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.background,
  },
  ageBadge: {
    alignSelf: "center",
    backgroundColor: "rgba(204, 85, 0, 0.1)",
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 15,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  ageText: { color: colors.primary, fontWeight: "bold", fontSize: 14 },
  label: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 6,
    marginLeft: 4,
    fontWeight: "600",
  },
  rowInputs: { flexDirection: "row", justifyContent: "space-between" },
  halfInput: { width: "48%" },
  readOnlyInput: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    color: colors.textPrimary,
    opacity: 0.8,
  },
  segmentContainer: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 10,
    marginBottom: 15,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
    width: "100%",
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  segmentButtonActive: { backgroundColor: colors.primary },
  segmentText: { color: colors.textSecondary, fontSize: 13, fontWeight: "600" },
  segmentTextActive: { color: colors.textPrimary },
  logoutButton: {
    flexDirection: "row",
    backgroundColor: "transparent",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    borderWidth: 1,
    borderColor: "#EF4444",
  },
  logoutText: { color: "#EF4444", fontSize: 16, fontWeight: "bold" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 30,
    paddingBottom: 50,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "bold",
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  settingLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "500",
  },
});
