import { StyleSheet } from "react-native";

// MUY IMPORTANTE: Debe ser una función que reciba 'colors'
export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    topTabs: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tabText: { fontSize: 16, color: colors.textSecondary, fontWeight: "600" },
    tabTextActive: {
      color: colors.primary,
      borderBottomWidth: 2,
      borderBottomColor: colors.primary,
      paddingBottom: 5,
    },
    content: { padding: 20, flex: 1 },
    searchBar: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      padding: 12,
      borderRadius: 10,
      alignItems: "center",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      color: colors.textPrimary,
      marginLeft: 10,
      fontSize: 16,
    },
    placeholderText: {
      color: colors.textSecondary,
      textAlign: "center",
      marginTop: 40,
    },
    userCard: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    userAvatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginRight: 15,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    userAvatarPlaceholder: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginRight: 15,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    usernameText: {
      flex: 1,
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: "600",
    },
    feedCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 15,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.border,
    },
    feedHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    feedAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    feedAvatarPlaceholder: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
      backgroundColor: colors.background,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    feedHeaderText: {
      flex: 1,
    },
    feedUsername: {
      color: colors.textPrimary,
      fontWeight: "bold",
      fontSize: 15,
    },
    feedAction: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 2,
    },
    feedTime: {
      color: colors.textSecondary,
      fontSize: 12,
    },
    feedContent: {
      backgroundColor: colors.background,
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    feedTitle: {
      color: colors.primary,
      fontWeight: "bold",
      fontSize: 16,
      marginBottom: 6,
    },
    feedStats: {
      flexDirection: "row",
      gap: 15,
    },
    feedStatText: {
      color: colors.textSecondary,
      fontSize: 13,
    },
  });
